|Módulo anterior|Índice|Módulo siguiente|
|-------|-----------|-----------------|
|[5.Entradas y salidas](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/5_Entradas_y_salidas.ipynb)|[Introducción](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/0_Introducción_a_Jupyter_notebooks.ipynb)|[7.Librería Pandas](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/7_Librer%C3%ADa_Pandas.ipynb)|

# MÓDULO 6: LIBRERÍA NUMPY

NumPy es una de las librerías más importantes de Python para el trabajo con datos numéricos. Permite crear y manipular arrays (vectores y matrices), realizar operaciones matemáticas eficientes y trabajar con grandes volúmenes de datos. Es ampliamente usada en análisis financiero, estadísticas y machine learning.

## Sección 1: Manejo de librerías (`import`)

Antes de usar cualquier librería externa en Python, es necesario importarla. En esta sección importamos NumPy y mostramos cómo crear un array básico para trabajar con números.

In [ ]:
# Importar NumPy
import numpy as np

# Crear un array
numeros = np.array([1, 2, 3, 4, 5])
print("Array:", numeros)

# Tipo del array
print("Tipo:", type(numeros))

Array: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>


## Sección 2: Estructuras de datos multidimensionales (arrays)

Los arrays en NumPy pueden tener más de una dimensión. Esto permite representar datos como matrices, algo común en economía y contabilidad. Aquí vemos cómo crear una matriz 2D y obtener información sobre su forma y dimensiones.

In [ ]:
# Crear array bidimensional
matriz = np.array([[1, 2], [3, 4], [5, 6]])
print("Matriz:")
print(matriz)

# Ver forma y dimensiones
print("Forma:", matriz.shape)
print("Dimensiones:", matriz.ndim)

Matriz:
[[1 2]
 [3 4]
 [5 6]]
Forma: (3, 2)
Dimensiones: 2


## Sección 3: Indexación y slicing

Una de las ventajas de NumPy es acceder fácilmente a elementos específicos de los arrays o seleccionar subconjuntos. Esta sección cubre cómo extraer valores individuales y subconjuntos usando indexación y slicing.

In [ ]:
# Indexación
print("Elemento fila 1, columna 0:", matriz[1, 0])

# Slicing
print("Primera columna:", matriz[:, 0])
print("Últimas dos filas:")
print(matriz[1:, :])

Elemento fila 1, columna 0: 3
Primera columna: [1 3 5]
Últimas dos filas:
[[3 4]
 [5 6]]


## Sección 4: Operaciones matemáticas con arrays

NumPy permite realizar operaciones matemáticas de manera muy eficiente. Podemos aplicar operaciones escalares a todos los elementos, hacer operaciones entre arrays y obtener estadísticas como media o desviación estándar.

In [ ]:
# Suma y producto escalar
print("Array original:", numeros)
print("Array + 10:", numeros + 10)
print("Array * 2:", numeros * 2)

# Operaciones entre arrays
otro = np.array([10, 20, 30, 40, 50])
print("Suma de arrays:", numeros + otro)

# Estadísticas
print("Media:", numeros.mean())
print("Desviación estándar:", numeros.std())

Array original: [1 2 3 4 5]
Array + 10: [11 12 13 14 15]
Array * 2: [ 2  4  6  8 10]
Suma de arrays: [11 22 33 44 55]
Media: 3.0
Desviación estándar: 1.4142135623730951


# MÓDULO 6: EJERCICIOS

1. Crea un array de 10 números del 1 al 10.
2. Crea una matriz 3x3 con los números del 1 al 9.
3. Extrae la segunda fila de la matriz.
4. Multiplica todos los elementos por 5.
5. Calcula la media y la suma total de los elementos.

In [2]:
#EJECUTA ESTA CELDA PARA PODER COMPROBAR LOS RESULTADOS DE LOS EJERCICIOS
!wget -O tests_curso.py https://raw.githubusercontent.com/Sergiodlgl/PyCourseADE/main/data/tests_curso.py
import tests_curso

import numpy as np

--2025-06-08 10:06:52--  https://raw.githubusercontent.com/Sergiodlgl/PyCourseADE/main/data/tests_curso.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 637 [text/plain]
Saving to: ‘tests_curso.py’

tests_curso.py      100%[===================>]     637  --.-KB/s    in 0s      

2025-06-08 10:06:53 (50.3 MB/s) - ‘tests_curso.py’ saved [637/637]



In [ ]:
s = np.array([-50,20,40])

np.irr([-50,20,40])

AttributeError: module 'numpy' has no attribute 'irr'

## Ejercicio 1: Análisis de rentabilidad de productos

Para este ejercicio se pide implementar una función que calcule la rentabilidad los productos de una empresa en un número de regiones dadas.

Como datos de entrada se saben:
* Un array de n precios
* Un array de n costes
* Un array bisimensional de m regiones y n productos

Un ejemplo de datos de entrada es:
```
    precios = np.array([10.0, 20.0, 15.0])
    costes = np.array([6.0, 12.0, 8.0])

    ventas = np.array([
        [100, 150, 200],   # Región 1
        [80, 130, 170],    # Región 2
        [120, 160, 180],   # Región 3
        [90, 140, 160]     # Región 4
    ])
```
El resultado de esa entrada sería:
```
    array([
        [ 400., 1200., 1400.],
        [ 320., 1040., 1190.],
        [ 480., 1280., 1260.],
        [ 360., 1120., 1120.]
    ])
```

In [ ]:
def calcular_clv(lista_ingresos_costes, tasa_descuento):
    # Tu código aquí

# COMPROBACIÓN DE LOS RESULTADOS
tests_curso.test_calcular_clv(calcular_clv)

In [6]:
precios = np.array([10.0, 20.0, 15.0])
costes = np.array([6.0, 12.0, 8.0])

ventas = np.array([
  [100, 150, 200],   # Región 1
  [80, 130, 170],    # Región 2
  [120, 160, 180],   # Región 3
  [90, 140, 160]     # Región 4
])

ventas * (precios - costes)

array([[ 400., 1200., 1400.],
       [ 320., 1040., 1190.],
       [ 480., 1280., 1260.],
       [ 360., 1120., 1120.]])

In [ ]:
# 1
array_10 = np.arange(1, 11)
print("Array de 1 a 10:", array_10)

# 2
matriz_3x3 = np.arange(1, 10).reshape(3, 3)
print("Matriz 3x3:")
print(matriz_3x3)

# 3
print("Segunda fila:", matriz_3x3[1])

# 4
print("Matriz x5:")
print(matriz_3x3 * 5)

# 5
print("Media:", matriz_3x3.mean())
print("Suma total:", matriz_3x3.sum())

Array de 1 a 10: [ 1  2  3  4  5  6  7  8  9 10]
Matriz 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Segunda fila: [4 5 6]
Matriz x5:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Media: 5.0
Suma total: 45


|Módulo anterior|Índice|Módulo siguiente|
|-------|-----------|-----------------|
|[5.Entradas y salidas](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/5_Entradas_y_salidas.ipynb)|[Introducción](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/0_Introducción_a_Jupyter_notebooks.ipynb)|[7.Librería Pandas](https://colab.research.google.com/github/Sergiodlgl/PyCourseADE/blob/main/7_Librer%C3%ADa_Pandas.ipynb)|